# Generated by Django 5.2.6 on 2025-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='materiais/')),
                ('unidade_medida', models.CharField(default='un', max_length=50)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
