# Generated by Django 5.2.6 on 2025-09-07 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemnotafiscal',
            old_name='nota',
            new_name='nota_fiscal',
        ),
        migrations.AlterField(
            model_name='itemnotafiscal',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.material'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
